- mcux/components/phyksz8081/fsl_phy.h
Used by https://github.com/zephyrproject-rtos/zephyr/pull/23413/files
> mcux: Add PHY_OMS_FACTORY_MODE_MASK definition for KSZ8081 PHY

- mcux/middleware/usb/device/usb_device_ehci.c
- mcux/middleware/usb/device/usb_device_ehci.h
Convert to use new DT_INST macros
> usb: usb_device_ehci: Update for new DT macros

- mcux/CMakeLists.txt
- mcux/README
- mcux/hal_nxp.cmake
- mcux/mcux-sdk/boards/evkmimxrt595/flash_config/flash_config.c
> Add RT595 support

- mcux/README
Add information related to changes made to mcux-sdk folder for MXRT1050 QSPI support
> Update REAME file

- mcux/hal_nxp.cmake
This commit enable lpc adc support
Signed-off-by: Navin Sankar Velliangiri <navin@linumiz.com>
> drivers/adc: Add lpc adc support

- mcux/hal_nxp.cmake
include SDIF driver for SDIO components
> mcux: include sdif driver

- mcux/hal_nxp.cmake
Update the hal CMAKE file to reflect the device specific nature and location of the code.
> Update for the lpc55s36 IAP device driver

- mcux/scripts/pinctrl/imx/imx_cfg_utils.py
Update gpio mux generation to create "gpio-reserved-ranges" property,
which encodes gaps in gpio pins for a given GPIO block, to allow the
gpio controller to select the correct pinmux setting from the pinmux
array property.
> scripts: pinctrl: update gpio mux generation

- s32/CMakeLists.txt
- s32/mcux/devices/S32K344/S32K344_device.h
- s32/mcux/devices/S32K344/S32K344_features.h
- s32/mcux/devices/S32K344/S32K344_glue_mcux.h
- s32/soc/s32k344/src/Clock_Ip_Cfg.c
Add FlexCAN instance base addresses and module features to support using FlexCAN MCUX driver.
> Add support for FLexCAN on S32K344

- mcux/README
- mcux/hal_nxp.cmake
- mcux/mcux-sdk/devices/MIMX8QM6/MIMX8QM6_dsp_features.h
- mcux/mcux-sdk/devices/MIMX8QM6/drivers/fsl_clock.c
- mcux/mcux-sdk/devices/MIMX8QM6/fsl_device_registers.h
- mcux/mcux-sdk/devices/MIMX8QM6/system_MIMX8QM6_dsp.c
- mcux/mcux-sdk/devices/MIMX8QM6/system_MIMX8QM6_dsp.h
- mcux/mcux-sdk/devices/MIMX8QX6/MIMX8QX6_dsp_features.h
- mcux/mcux-sdk/devices/MIMX8QX6/fsl_device_registers.h
- mcux/mcux-sdk/devices/MIMX8QX6/scfw_api/main/ipc_imx8qx.c
- mcux/mcux-sdk/devices/MIMX8QX6/system_MIMX8QX6_dsp.c
- mcux/mcux-sdk/devices/MIMX8QX6/system_MIMX8QX6_dsp.h
Depends on: https://github.com/nxp-mcuxpresso/mcux-sdk/pull/144
> Add support for i.MX8QM's and i.MX8QXP's DSP core

- mcux/README
- mcux/hal_nxp.cmake
- mcux/mcux-sdk/devices/MIMX8ML8/MIMX8ML8_dsp_features.h
- mcux/mcux-sdk/devices/MIMX8ML8/drivers/fsl_clock.h
- mcux/mcux-sdk/drivers/irqsteer/fsl_irqsteer.c
- mcux/mcux-sdk/drivers/irqsteer/fsl_irqsteer.h
Depends on https://github.com/nxp-mcuxpresso/mcux-sdk/pull/146.
> devices: MIMX8ML8: Add support for new IRQSTEER driver

- mcux/hal_nxp.cmake
Add support for including DMIC driver into build
> mcux: hal_nxp: add support for DMIC

- mcux/README
- mcux/mcux-sdk/drivers/caam/fsl_caam.c
This reverts commit 75c1e0ddf2937b7a46839d918bb2098cbe1c961e.
> Revert "caam: Fixes RNG descriptors"

- mcux/README
- mcux/mcux-sdk/drivers/caam/fsl_caam.c
Reverts zephyrproject-rtos/hal_nxp#320
> Revert "Revert "caam: Fixes RNG descriptors""

- mcux/hal_nxp.cmake
- mcux/mcux-sdk/drivers/mcx_romapi/driver_flashiap.cmake
> build: hal_nxp: Add support for MCX Flash

- mcux/README
- mcux/mcux-sdk/devices/MIMX8UD7/MIMX8UD7_dsp1_features.h
- mcux/mcux-sdk/devices/MIMX8UD7/drivers/driver_reset.cmake
- mcux/mcux-sdk/devices/MIMX8UD7/fsl_device_registers.h
- mcux/mcux-sdk/devices/MIMX8UD7/system_MIMX8UD7_dsp1.c
- mcux/mcux-sdk/devices/MIMX8UD7/system_MIMX8UD7_dsp1.h
Depends on: https://github.com/nxp-mcuxpresso/mcux-sdk/pull/180
> devices: MIMX8UD7: add support for 8ULP's HIFI4 DSP core

- mcux/hal_nxp.cmake
Add build support for GAU DAC and ADC
> mcux: Add GAU DAC and ADC driver builds

- mcux/CMakeLists.txt
need OCOTP driver to get device ID
> mcux: RW OCOTP if HWINFO

- mcux/hal_nxp.cmake
Add the cache files needed for MCXN947 FlexSPI driver
> build: Add cache files to MCX build

- mcux/mcux-sdk/devices/MCXN947/drivers/driver_edma_soc.cmake
Add the SoC DMA cmake file for MCXN947
> cmake: Add SoC DMA file for MCXN947

- mcux/scripts/pinctrl/README.md
- mcux/scripts/pinctrl/gen_board_pinctrl.py
- mcux/scripts/pinctrl/gen_soc_headers.py
- mcux/scripts/pinctrl/kinetis/kinetis_cfg_utils.py
Add support for pin control generation for MCXN9x SOCs.
> scripts: pinctrl: support MCXN9x

- mcux/hal_nxp.cmake
Need OCOTP for ENET mac fused address
> mcux: OCOTP for ENET mac fuse

- mcux/README
- mcux/mcux-sdk/drivers/cache/cache64/fsl_cache.c
- mcux/mcux-sdk/drivers/cache/cache64/fsl_cache.h
- mcux/mcux-sdk/drivers/common/fsl_common_arm.h
These changes have been submitted to the SDK team.
> Fix mcux SDK cache64 driver

- mcux/README
- mcux/mcux-sdk/devices/MIMX9596/drivers/fsl_edma_soc_rev2.h
- mcux/mcux-sdk/drivers/edma_rev2/fsl_edma_rev2.c
- mcux/mcux-sdk/drivers/edma_rev2/fsl_edma_rev2.h
Depends on https://github.com/nxp-mcuxpresso/mcux-sdk/pull/211.
> add edma rev2 support for i.MX95

- .gitignore
- zephyr/blobs/license/LA_OPT_NXP_Online_Code_Hosting.txt
- zephyr/module.yml
Register MCXW72 NBU ble firmware in west blobs.
> zephyr: blobs: add MCXW72 NBU ble firmware blob

- zephyr/module.yml
upgrade rw612 FW version to 6.p37.
> zephyr: upgrade rw612 FW version to 6.p37

- dts/nxp/nxp_imx/mimx9131cvvxj-pinctrl.dtsi
Generate the pinctrl dtsi for mimx9131cvvxj using the latest MCUX config data.
> dts: nxp: nxp_imx: update the pinctrl dtsi for mimx9131cvvxj

- zephyr/module.yml
Added i.MX95 blobs and spsdk runner support.
> Add i.MX95 blobs and spsdk runner

- mcux/middleware/wifi_nxp/wifidriver/incl/mlan_fw.h
- mcux/middleware/wifi_nxp/wifidriver/wifi.c
Updated command parameter for wmm initialisation.
> mcux: wifi_nxp: Updated wmm init command

- mcux/mcux-sdk-ng/drivers/kpp/CMakeLists.txt
- mcux/mcux-sdk-ng/drivers/kpp/fsl_kpp.c
- mcux/mcux-sdk-ng/drivers/kpp/fsl_kpp.h
1.Optimize rowData debounce method to adapt to multi-key detection
2.Modify the KPP_keyPressScanning type to status_t.
> drivers:kpp:support kpp driver multiple key detection.
