zephyrproject-rtos/hal_nxp

mcux/scripts/import_mcux_sdk.py
After moving the NXP HAL to its own module, the import script does not
work anymore, as the destination paths have changed. Update them so the
script copies SDK files to the proper directories.
Signed-off-by: Filip Brozovic <fbrozovic@gmail.com>
=> mcux: adjust paths in import script after moving HAL to module

mcux/drivers/lpc/CMakeLists.txt
Added fsl_spi.c and fsl_flexcomm.c when building Flexcomm's SPI driver
Signed-off-by: Andrei Gansari <andrei.gansari@nxp.com>
Work with https://github.com/zephyrproject-rtos/zephyr/pull/17322
=> drivers: build spi targets

mcux/README
The PTP patches are now in the upstream SDK HALs so we don't need
comments about those patches anymore.
=> README: remove comments on PTP patches

mcux/drivers/kinetis/CMakeLists.txt
The compile definition ENET_ENHANCEDBUFFERDESCRIPTOR_MODE has been
added by modifying the build environment of the 'zephyr' library. But
modifying this library is not supported.
The intention was to modify the global build environment, so we change
to use the zephyr_ API instead of the zephyr_library_ API as this API
will behave as intended.
Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>
=> cmake: Fix how compile definition is added

mcux/devices/LPC54114/gcc/startup_LPC54114_cm4.S
This commit removes unnecessary inclusion of offsets_short.h in the
LPC54114 start-up code.
The offsets_short.h is a kernel private header and must not be included
by non-kernel components. The kernel and arch private header
directories will be removed from the compiler include path in the near
future.
For more details, Refer to the issue zephyrproject-rtos/zephyr#20119.
Signed-off-by: Stephanos Ioannidis <root@stephanos.io>
=> lpc54114: Remove offsets_short.h inclusion.

imx/drivers/CMakeLists.txt
The imx6/7 soc init always requires clock control module (ccm) drivers
from the hal, so there is no need for ifdefs.
Signed-off-by: Maureen Helm <maureen.helm@nxp.com>
cc: @ulfalizer
=> imx: Compile clock drivers unconditionally

mcux/boards/CMakeLists.txt
When more mcux boards are added, the new ".boot_hdr.conf" and ".boot_hdr.dcd_data" will be placed in zephyr / board/arm/new_board, No need to add more MCUX_BOARD to mcux/boards
Signed-off-by: Frank Li <lgl88911@163.com>
=> cmake: support offload board

mcux/drivers/lpc/CMakeLists.txt
Renames CONFIG_USART_MCUX_LPC to CONFIG_UART_MCUX_FLEXCOMM to more
accurately reflect the flexcomm hardware IP and to prepare for
instantiating it on an SoC outside the LPC family.
Signed-off-by: Maureen Helm <maureen.helm@nxp.com>
=> mcux: Rename lpc usart shim driver config

mcux/middleware/usb/device/port/zephyr/usb_dc_mcux.h
Zephyr no longer adds the drivers subdirectory of the include
hierarchy to the search path, so references to driver headers must
include the drivers/ prefix.
Signed-off-by: Peter Bigot <peter.bigot@nordicsemi.no>
=> zephyr: fix driver include paths

mcux/drivers/lpc/CMakeLists.txt
Builds the lpc flexcomm i2c hal driver when the corresponding shim
driver is enabled.
Signed-off-by: Maureen Helm <maureen.helm@nxp.com>
=> mcux: Build lpc flexcomm i2c driver

mcux/drivers/kinetis/CMakeLists.txt
Add support for compiling the DAC or DAC32 source files if CONFIG_DAC_MCUX_DAC or CONFIG_DAC_MCUX_DAC32 is enabled.
Signed-off-by: Henrik Brix Andersen <henrik@brixandersen.dk>
=> mcux: drivers: kinetis: add DAC and DAC32 support

mcux/drivers/kinetis/CMakeLists.txt
The TPM (Timer/PWM Module) is a 2- to 8-channel timer which
supports input capture, output compare, and the generation of
PWM signals to control electric motor and power management
applications.
Signed-off-by: Alex Porosanu <alexandru.porosanu@nxp.com>
=> drivers: kinetis: enable support for the TPM driver

mcux/middleware/usb/device/port/zephyr/usb_dc_mcux.h
Convert to use C99 types as we intend to deprecate the zephyr
specific integer types.
=> usb: Convert from Zephyr to C99 types

mcux/README, mcux/drivers/imx/fsl_lpspi.c, mcux/drivers/kinetis/fsl_lpspi.c
After the master transfer is completed,
if the sr flag is not clear, the callback of the transfer
completion will be called again in other interrupts.
Signed-off-by: Frank Li <lgl88911@163.com>
=> mcux: drivers: imx: fix Other interrupts treated as transfer completion

mcux/README, mcux/drivers/lpc/fsl_spi.c
Allow receving SPI data without saving it, i.e. Rx buffer is NULL.
Signed-off-by: Andrei Gansari <andrei.gansari@nxp.com>
=> drivers: lpc: fsl_spi allow NULL Rx

mcux/middleware/usb/device/usb_device_ehci.h
The define for USB_DEVICE_CONFIG_ENDPOINTS erroneously divided
the DTS value for number of USB endpoints by 2.
=> mcux: usb: Fix USB_DEVICE_CONFIG_ENDPOINTS definition

mcux/boards/CMakeLists.txt
The CONFIG_FLASH_SIZE has the flash size in KB, need to specify the value in bytes as is expected by the Flash configuration code. This should fix https://github.com/zephyrproject-rtos/zephyr/issues/28206
=> MXRT600: Fix BOARD_FLASH_SIZE

mcux/drivers/imx/CMakeLists.txt
This has been fixed on kinetis devices by
commit#47914cb291b3cfdea8248bd15787d7d733f71729.
Similar change is needed for iMXRT devices
=> drivers: cmake: Fix how compile definition is added

mcux/drivers/imx/CMakeLists.txt
Builds the imx flexcan driver when the corresponding shim driver is
enabled.
Signed-off-by: Maureen Helm <maureen.helm@nxp.com>
=> mcux: Build imx flexcan driver

mcux/drivers/imx/CMakeLists.txt
We need to same ASSERT/NDEBUG support that exists for kinetis for imx.
Otherwise we get build errors with building the flexcan drivers on
imx-rt.
=> iMX: can: Fix building flexcan driver

mcux/drivers/lpc/fsl_iap_kbp.h, mcux/drivers/lpc/fsl_iap_skboot_authenticate.h
The import of SDK 2.8.2 missed adding these files that are new.  Causes
issues when trying to build the IAP flash driver.
=> LPC: Add missing fsl_iap* files from SDK 2.8.2

mcux/middleware/usb/device/port/zephyr/usb_dc_mcux.h, mcux/middleware/usb/device/usb_device_ehci.c
Re-add fields that were deleted as part of the update. This is a fix for issue https://github.com/zephyrproject-rtos/zephyr/issues/29710.
Tested Zephyr USB HID tests on MXRT devices.
=> usb: Fix build errors due to update to SDK 2.8

dts/nxp/kinetis/MKW40Z160VHT4-pinctrl.dtsi
Add the pin configuations we need specifically for the Hexiwear KW40Z
as its the only board utilizing this SoC.
=> dts: nxp: kinetis: populate MKW40Z pinctrl dtsi

mcux/drivers/imx/CMakeLists.txt, mcux/drivers/imxrt6xx/CMakeLists.txt
Relocates the i.MX RT FlexSPI driver to the configured memory target if required.
This commit is needed for https://github.com/zephyrproject-rtos/zephyr/pull/33701
=> mcux: Relocate FlexSPI driver with XIP

mcux/CMakeLists.txt
Relocates the i.MX RT685 power driver to SRAM when CONFIG_PM is enabled
Signed-off-by: Mahesh Mahadevan <mahesh.mahadevan@nxp.com>
=> MXRT600: Relocate power driver to SRAM

mcux/drivers/imxrt6xx/CMakeLists.txt
Builds the RT600 RTC driver when the corresponding counter shim driver is enabled.
=> RT600: Add SDK RTC driver

mcux/drivers/kinetis/CMakeLists.txt
Compile fsl_lptmr.c if either CONFIG_COUNTER_MCUX_LPTMR or CONFIG_MCUX_LPTMR_TIMER is enabled.
Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>
=> mcux: drivers: kinetis: add LPTMR OS timer support

mcux/CMakeLists.txt, mcux/middleware/usb/CMakeLists.txt
It is planned to remove the config option USB (CONFIG_USB)
in upstream project. Replace it with CONFIG_USB_DEVICE_DRIVER.
See https://github.com/zephyrproject-rtos/zephyr/pull/36630
=> mcux: usb: replace CONFIG_USB with CONFIG_USB_DEVICE_DRIVER

mcux/drivers/imxrt6xx/CMakeLists.txt
Builds the RT600 TRNG driver when the corresponding
CONFIG_ENTROPY_MCUX_TRNG flag is set.
=> RT600: Add SDK TRNG driver

mcux/drivers/imx/CMakeLists.txt
add SDK support for rt1170's lpadc driver
Signed-off-by: Crist Xu <crist.xu@nxp.com>
=> driver: lpadc: add support for the lpadc driver

mcux/drivers/imxrt6xx/CMakeLists.txt
Enable the build of fsl_wwdt.c watchdog driver if enabled by
Zephyr build.
=> watchdog: Enable build of watchdog driver for imxrt6xx

zephyr/module.yml
Move to using cmake-ext/kconfig-ext which means we'll look in the
zephyr repo for cmake and kconfig files.  This allows us to put
zephyr specific integrations with zephyr itself.
We'll have the zephyr side cmake include the module cmake so this
should effectively be transparent at this point.  (we'd do the same
for kconfig, but there are no kconfig files in this repo).
=> zephyr/module.yml: Update to use cmake-ext/kconfig-ext

mcux/drivers/lpc/CMakeLists.txt
SDK split out some stuff from fsl_common.c into fsl_common_arm.c so
we ned to build that as well (similar to what is already happening
for imx and imxrt6xx).
(Fixes build issue with watchdog driver needing SDK_DelayAtLeastUs)
=> Fix LPC builds post SDK 2.10.0 update

mcux/drivers/imxrt6xx/CMakeLists.txt
Builds the RT600 LPADC driver when the corresponding
CONFIG_ADC_MCUX_LPADC flag is set.
=> RT600: Add SDK LPADC Driver

mcux/README, mcux/devices/MKE16F16/MKE16F16.h, mcux/devices/MKE18F16/MKE18F16.h
Fix the size of mailbox registers (the KE1xF has 16 mailboxes, not 64). Fix the offset of the RXIMR registers.
Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>
=> mcux: devices: mke1xf: fix CAN_Type number of mailboxes

mcux/drivers/lpc/CMakeLists.txt
This driver is used to add PWM support
=> drivers: lpc: Add SCTimer SDK driver

mcux/CMakeLists.txt
CMake include if statement was not correctly including the Cortex M4 cache driver file when targeting the Cortex M4 on RT11xx platforms, which caused a linker failure when building drivers requiring the cache driver.
=> devices: rt11xx: Fix CMake include for RT11xx CM4 cache file

mcux/devices/MIMXRT685S/MIMXRT685S_cm33.h, mcux/devices/MIMXRT685S/MIMXRT685S_dsp.h
Rename the GPIO INPUTMUX_PINT_SEL from INPUTMUX_PINT_SEL_COUNT
to INPUTMUX_PINTSEL_COUNT.
Signed-off-by: Navin Sankar Velliangiri <navin@linumiz.com>
Fixes: [37148](https://github.com/zephyrproject-rtos/zephyr/pull/37148) build failure.
=> MIMXRT685S: Rename INPUTMUX_PINT_SEL count

mcux/CMakeLists.txt, mcux/hal_nxp.cmake, mcux/mcux-sdk/devices/MIMXRT595S/device_system.cmake, mcux/mcux-sdk/devices/MIMXRT685S/device_system.cmake
Include the `system_xxx.c` file that the SDK provides into the zephyr build.
=> cmake: Include system_xxx.c file

mcux/hal_nxp.cmake
System cmake files for RT11xx platforms are named differently
=> cmake: Fix include of sys cmake files for RT11xx

mcux/hal_nxp.cmake, mcux/mcux-sdk/drivers/pmu/driver_pmu.cmake
Adds required include file definitions to NXP HAL cmake file, to include the PMU, GPC, and DCDC hal drivers. Additionally updates MCUX HAL to commit `81a42c9e5875b70f0acdf10c23aa977ce1135100`, which includes the required driver cmake file to the PMU component.
=> Enable Power Management HAL drivers

mcux/hal_nxp.cmake, mcux/mcux-sdk/boards/evkbimxrt1050/xip/driver_xip_board_evkbimxrt1050_qspi.cmake, mcux/mcux-sdk/boards/evkbimxrt1050/xip/evkbimxrt1050_flexspi_nor_qspi_config.c
Add support for mimxrt1050_evk_qspi. This board should support both
boot-from-hyperflash and boot-from-qspi. This modification enables a
modified board to boot from the on-board qspi nor chip.
Signed-off-by: Xabier Marquiegui <xmarquiegui@ainguraiiot.com>
=> mcux: Add support for mimxrt1050_evk_qspi

mcux/hal_nxp.cmake
Fix for Zephyr Issue https://github.com/zephyrproject-rtos/zephyr/issues/42171
=> hal_cmake: Include system.c for MXRT6xx and MXRT5xx

mcux/hal_nxp.cmake
RT11xx has soc specific system reset controller driver. Enable inclusion
of this driver, and only include generic SOC driver if not building for
RT11xx
=> mcux: Enable inclusion of soc_src driver for RT11xx

mcux/README, mcux/mcux-sdk/drivers/sai/fsl_sai.c, mcux/mcux-sdk/drivers/sai/fsl_sai.h
corrected macro name in fsl_sai driver to match *_features.h headers
Signed-off-by: Derek Snell <derek.snell@nxp.com>
=> mcux_sai: FSL_FEATURE_SAI_HAS_ON_DEMAND_MODE

mcux/hal_nxp.cmake
Add USDHC driver include. The is required to enable the USDHC hal driver used in the NXP SD host controller driver in the SD subsystem.
=> Added usdhc driver include

imx/drivers/CMakeLists.txt
This commit enable imx6sx adc.
This commit is needed by https://github.com/zephyrproject-rtos/zephyr/pull/40355
=> drivers/adc: imx6sx ADC support.

dts/nxp/nxp_imx/rt/mimxrt1011cae4a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1011dae5a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1015caf4a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1015daf5a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1021caf4a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1021cag4a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1021daf5a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1021dag5a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1024cag4a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1024dag5a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1052cvj5b-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1052cvl5b-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1052dvj6b-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1052dvl6b-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1062cvj5a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1062cvl5a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1062dvj6a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1062dvl6a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1064cvj5a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1064cvl5a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1064dvj6a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1064dvl6a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1166cvm5a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1166dvm6a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1166xvm5a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1176avm8a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1176cvm8a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1176dvmaa-pinctrl.dtsi
Update iMX RT pinctrl nodes with /omit-if-no-ref/ to reduce size of
generated devicetree header.
=> dts: update iMX RT pinctrl nodes with /omit-if-no-ref/ property

mcux/CMakeLists.txt, mcux/quick_access.ld
SDK defines CodeQuickAccess and DataQuickAccess sections for
locating critical items that need faster access. Centralize the
handling of these sections instead of doing it per SOC.
Fixes #44452
=> hal: nxp: Centralize handling of SDK custom sections

mcux/hal_nxp.cmake
Add the SDK support for the rt1170
Signed-off-by: Crist Xu <crist.xu@nxp.com>
=> hal: display: add mipi dsi support for the rt1170

mcux/hal_nxp.cmake
The LPC ADC driver was accidentally removed in a previous change.
Adding it back in.
=> mcux: lpc: add back LPC adc driver

mcux/CMakeLists.txt, mcux/quick_access_code.ld, mcux/quick_access_data.ld
Link SDK's CodeQuickAccess symbols to the ramfunc section. This is dependent on Zephyr PR #[44850](https://github.com/zephyrproject-rtos/zephyr/pull/44850)
=> mcux: Update linking SDK symbols DataQuickAccess & CodeQuickAccess

dts/nxp/nxp_imx/rt/mimxrt1062cvj5a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1062cvl5a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1062dvj6a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1062dvl6a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1064cvj5a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1064cvl5a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1064dvj6a-pinctrl.dtsi, dts/nxp/nxp_imx/rt/mimxrt1064dvl6a-pinctrl.dtsi
RT1060 and RT1064 have missing DAISY register definitions for some
pinmux selections. Fix these values using fsl_iomuxc.h as a ground
truth.
=> dts: nxp: rt: fix up daisy register values for RT1064 and RT1060

mcux/scripts/imx_cfg_utils.py, mcux/scripts/imx_fixup_pinmux.py, mcux/scripts/imx_gen_dts.py, mcux/scripts/imx_gen_gpio.py, mcux/scripts/imx_gen_headers.py
Add initial script to generate pinctrl groups from MEX file for iMX.RT
parts. This script uses the files provided in MCUXpresso config tools offline data
(downloadable from MCUXpresso SDK builder), combined with a MEX configuration file (editable with MCUXpresso config tools),
to automatically generate pinctrl groups for a given board.
Pinctrl groups can be handcoded without the aid of this script, it is only made available to simplify generation of pinctrl groups for NXP boards.
=> Add script to generate pin control headers and pin control groups for iMX RT parts

mcux/middleware/wireless/framework_5.3.3/OSAbstraction/Source/fsl_os_abstraction_zephyr.c
Zephyr has prefixed all of its includes with <zephyr/...>. While the old
mode can still be used (CONFIG_LEGACY_INCLUDE_PATH) and is still enabled
by default, it's better to be prepared for its removal in the future.
=> zephyr: update include paths to use <zephyr/...>

mcux/hal_nxp.cmake
Include missing ADC External Trigger Control driver.
Signed-off-by: Bartosz Bilas <b.bilas@grinn-global.com>
=> mcux: include adc etc driver

mcux/scripts/lpc_cfg_utils.py, mcux/scripts/lpc_gen_dts.py, mcux/scripts/lpc_gen_headers.py
Add lpc configuration parsing scripts. These scripts are capable of
parsing a signal_configuration.xml file for an LPC or iMX RT 3 digit
part, and generating an output pin control header file as well as pin
control dtsi file containing pin mux options.
=> mcux: scripts: add lpc configuration scripts

mcux/README, mcux/mcux-sdk/devices/MIMXRT685S/MIMXRT685S_cm33.h, mcux/mcux-sdk/devices/MIMXRT685S/MIMXRT685S_dsp.h
This variation in the macro name is now handled inside zephyr soc.h file as this will not be fixed inside mcux-sdk.
=> MIMXRT685S: Revert Rename of INPUTMUX_PINT_SEL

mcux/CMakeLists.txt, mcux/nocache.ld
Link SDK NonCacheable symbol into the nocache section. This is dependent on Zephyr PR#[49368](https://github.com/zephyrproject-rtos/zephyr/pull/49368)
=> mcux: Link SDK symbols NonCacheable

mcux/CMakeLists.txt
Signed-off-by: Jiafei Pan <Jiafei.Pan@nxp.com>
=> cmake: use mcux-sdk's CMSIS for cortex-A Cores

mcux/README, mcux/mcux-sdk/drivers/caam/fsl_caam.c
Moves CAAM initialization and RNG related job descriptors to a non-cacheable region instead of being on the write-back stack. Currently the CAAM and core(s) are accessing these descriptors incoherently.
Signed-off-by: Declan Snyder <declan.snyder@nxp.com>
=> caam: Fixes RNG descriptors

mcux/hal_nxp.cmake
Remove board related definitions, as well as flash configuration includes from NXP HAL cmake. Although the board configuration files are still present, they are now included from board directories in tree, so that customers porting Zephyr to a custom board face less challenges locating the relevant file.
=> cmake: remove board definitions and flash configuration includes

mcux/hal_nxp.cmake
Only relocate flexSPI driver when CONFIG_FLASH=y.
CONFIG_FLASH_MCUX_FLEXSPI_XIP previously was dependent on CONFIG_FLASH, but the scope of this Kconfig has changed. Due to this, the flexSPI driver now must have two checks, as it should not relocated when the driver is being used for a memory controller that does not expose the flash driver interface
=> mcux: hal_nxp: only relocate flexSPI driver when CONFIG_FLASH=y

mcux/hal_nxp.cmake, mcux/mcux-sdk/devices/MK82F25615/device_system.cmake, mcux/mcux-sdk/devices/MKL25Z4/device_system.cmake, mcux/mcux-sdk/devices/MKW24D5/device_system.cmake, mcux/mcux-sdk/devices/MKW40Z4/device_system.cmake, mcux/mcux-sdk/devices/MKW41Z4/device_system.cmake
Add CMSIS SystemInit cmake files where required, and include device_system cmake for all SOCs, as this is where the CMSIS SystemInit function is defined.
=> mcux: add CMSIS SystemInit cmake files where required

mcux/hal_nxp.cmake
Add quadrature encoder driver (enc)
Related: https://github.com/zephyrproject-rtos/zephyr/issues/52211
Signed-off-by: Jeppe Odgaard <jeppe.odgaard@prevas.dk>
=> mcux: include enc driver

mcux/README, mcux/hal_nxp.cmake
Include device_system cmake file unconditionally for NXP SOCs. The files sourced by device_system implement CMSIS SystemInit, and also define core clock variables used by some RT series SOCs.
Add notes to the README patch list specifying SOCs which have had device_system files added.
=> mcux: include device_system unconditionally

mcux/README, mcux/mcux-sdk/drivers/flexcan/fsl_flexcan.c
Propagate kStatus_FLEXCAN_RxOverflow status when using the FlexCAN transactional APIs.
Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>
=> mcux: mcux-sdk: driver: flexcan: propagate kStatus_FLEXCAN_RxOverflow

mcux/hal_nxp.cmake
Include device_system conditionally, when PLATFORM_SPECIFIC_INIT Kconfig is enabled. RT6xx series uses variables defined by the device_system module in every build, so the file must be included unconditionally for it.
=> mcux: include device_system conditionally

mcux/hal_nxp.cmake
Update hal_nxp.cmake to use new zephyr_code_relocate API to relocate flexSPI flash driver to ITCM
=> mcux: Update hal_nxp.cmake to use new zephyr_code_relocate API

mcux/README, mcux/mcux-sdk/drivers/caam/fsl_caam.c
The templateRng descriptor used by CAAM_RNG_GetRandomDataNonBlocking() sets the PR (predictive ressitance) bit for each RNG request. This forces the hardware to regenerate entropy and reseed the DRBG on each request.
Cost on a 4000 byte rng request:
- with reseed: 130+ ms
- without reseed: 39 us
on a 4 byte request it is 130 ms versus 3us
=> mcux: fsl_caam: Fix forced reseed on each RNG request

mcux/README, mcux/mcux-sdk/drivers/common/fsl_common.h
Added 'zephyrisms' back to fsl_common.h
Updated readme
=> NXP HAL fixups for 2.13

mcux/mcux-sdk/drivers/caam/fsl_caam.c
Some of the changes from commit d957472002a3758154f402e982d95ce90cf58e12 were undone as part of SDK 2.13 update
=> mcux: caam: Fix errors from SDK 2.13 update

mcux/README, mcux/mcux-sdk/drivers/flexcomm/fsl_i2c.c, mcux/mcux-sdk/drivers/flexcomm/fsl_i2c.h
Patch to address driver not properly reporting if slave node is present on bus.
Fixes #57858
=> mcux: flexcom: i2c: Fix slave report

mcux/CMakeLists.txt, mcux/hal_nxp.cmake, mcux/nocache.ld
Enable DCP support for mcux platform.
~One remaining issue is that I get a linker warning:~
```
warning: orphan section `NonCacheable.init' from `modules/hal_nxp/hal_nxp/lib..__modules__hal__nxp.a(fsl_dcp.c.obj)' being placed in section `NonCacheable.init'
```
=> mcux: cmake: include Data Co-Processor (DCP)

s32/drivers/s32k3/Mcu/CMakeLists.txt
Remove Kconfig option and build always the sources unconditionally because it's used at SoC initialization.
=> s32k3: remove CONFIG_NXP_S32_PM

mcux/README, mcux/hal_nxp.cmake, mcux/mcux-sdk/devices/MIMX8QM6/MIMX8QM6_ca53_features.h, mcux/mcux-sdk/devices/MIMX8QM6/device_CMSIS.cmake, mcux/mcux-sdk/devices/MIMX8QM6/drivers/fsl_clock.c, mcux/mcux-sdk/devices/MIMX8QM6/drivers/fsl_clock.h, mcux/mcux-sdk/devices/MIMX8QM6/fsl_device_registers.h, mcux/mcux-sdk/devices/MIMX8QM6/system_MIMX8QM6_ca53.c, mcux/mcux-sdk/devices/MIMX8QM6/system_MIMX8QM6_ca53.h
This PR introduces the necessary changes for supporting MIMX8QM6's CA53 cores with Zephyr.
=> devices: MIMX8QM6: Add support for MIMX8QM6's CA53 cores

s32/mcux/devices/S32K344/S32K344_features.h, s32/mcux/devices/S32K344/S32K344_glue_mcux.h
Add LPI2C instance base addresses and module features to support using LPI2C MCUX driver.
=> Add support for LPI2C on S32K344

mcux/README, mcux/mcux-sdk/drivers/lpspi/fsl_lpspi.h, s32/mcux/devices/S32K344/S32K344_features.h, s32/mcux/devices/S32K344/S32K344_glue_mcux.h
Configure LPSPI features and allow to build this driver for S32K344.
LPSPI is affected by errata ERR050456 on this device, as described in S32K3X4-0P55A-1P55A-ERRATA.
The user can reset the transmit FIFO using LPSPIn_CR[RTF] bit and can reset the receive FIFO using LPSPIn_CR[RRF]. However, resetting the FIFO using CR[RTF] and CR[RRF] does not clear the FIFO pointers completely. Workaround this by resetting resetting the entire module using LPSPIn_CR[RST] bit.
=> Add support for LPSPI on S32K344

CMakeLists.txt
Rename module from `S32` to `NXP_S32` to avoid ambiguity. All other files and symbols have been already renamed but this was missing to update.
=> modules: rename S32 to NXP_S32

s32/drivers/s32k3/BaseNXP/include/Compiler.h, s32/drivers/s32ze/BaseNXP/include/Compiler.h
It is wrong to use toolchain-specific headers.
=> s32: use zephyr/toolchain.h

mcux/mcux-sdk/CMSIS/Core_AArch64/Include/core_common.h
There's already a definition of this register in the main repo code base, add a guard around it so it does not get redefined, fixes a build warning.
=> CMSIS: AArch64: avoid redefining MPIDR_AFFLVL_MASK

mcux/hal_nxp.cmake
new Zephyr ENET driver uses HAL ENET driver.
Also remove duplicate MCUX ENET inclusion.
=> hal_nxp: Include enet driver if using enet

mcux/README, mcux/mcux-sdk/drivers/pit/fsl_pit.c, s32/drivers/s32ze/BaseNXP/header/S32Z2_PIT.h, s32/mcux/devices/S32Z27/S32Z27_features.h, s32/mcux/devices/S32Z27/S32Z27_glue_mcux.h, s32/mcux/devices/S32Z27/device_CMSIS.cmake, s32/mcux/devices/S32Z27/device_system.cmake, s32/mcux/devices/S32Z27/drivers/driver_reset.cmake, s32/mcux/devices/S32Z27/drivers/fsl_clock.h, s32/mcux/devices/S32Z27/fsl_device_registers.h
Introduce necessary glue code and definitions to build MCUX with S32Z27 devices so that we can reuse existing shim drivers for common NXP hw blocks, same as it was done for S32K3. For now only PIT is supported.
A patch on MCUX is added for fixing compiler warnings, also fixed in https://github.com/nxp-mcuxpresso/mcux-sdk/pull/142
=> Support PIT for S32Z27

mcux/mcux-sdk/CMSIS/Core_AArch64/Include/core_common.h
Sync MPIDR_AFFLVL_MASK with Zephyr to avoid building warning for redefinition.
=> Fix mpid redefined

s32/drivers/s32k3/Icu/CMakeLists.txt, s32/drivers/s32k3/Icu/include/Emios_Icu_Ip.h, s32/drivers/s32k3/Icu/include/Emios_Icu_Ip_Irq.h, s32/drivers/s32k3/Icu/include/Emios_Icu_Ip_TrustedFunctions.h, s32/drivers/s32k3/Icu/include/Emios_Icu_Ip_Types.h, s32/drivers/s32k3/Icu/src/Emios_Icu_Ip.c, s32/drivers/s32k3/Icu/src/Emios_Icu_Ip_Irq.c, s32/soc/s32k344/include/Emios_Icu_Ip_Cfg.h, s32/soc/s32k344/include/Emios_Icu_Ip_Defines.h, s32/soc/s32k344/include/Emios_Icu_Ip_SA_Init_PBcfg.h, s32/soc/s32k344/include/Emios_Mcl_Ip_Cfg_Defines.h, s32/soc/s32k344/include/Emios_Pwm_Ip_Cfg.h, s32/soc/s32k344/include/Emios_Pwm_Ip_Init_PBcfg.h
This add bare-metal driver for eMIOS ICU and specific configuration for S32K344. EMIOS ICU driver will be used
for PWM pulse capture
=> Add bare-metal driver for eMIOS ICU for S32K344

mcux/hal_nxp.cmake
Remove CONFIG_IPM_IMX_REV2, as this Kconfig has been removed from Zephyr in favor of CONFIG_IPM_IMX (since both Kconfigs handled the same IP block)
=> mcux: hal_nxp: remove CONFIG_IPM_IMX_REV2

s32/drivers/s32k3/BaseNXP/header/S32K344_QUADSPI.h, s32/drivers/s32k3/BaseNXP/header/S32K344_SIUL2.h, s32/drivers/s32k3/BaseNXP/header/S32K344_WKPU.h, s32/drivers/s32ze/BaseNXP/header/S32Z2_CANXL_SIC.h, s32/drivers/s32ze/BaseNXP/header/S32Z2_LINFLEXD.h, s32/drivers/s32ze/BaseNXP/header/S32Z2_NETC_F1.h, s32/drivers/s32ze/BaseNXP/header/S32Z2_RTU_MRU.h, s32/drivers/s32ze/BaseNXP/header/S32Z2_SIUL2.h, s32/drivers/s32ze/BaseNXP/header/S32Z2_SPI.h, s32/drivers/s32ze/BaseNXP/header/S32Z2_STM.h, s32/drivers/s32ze/BaseNXP/header/S32Z2_SWT.h
At present, many of the NXP S32 shim drivers do not make use of devicetree instance-based macros because the NXP S32 HAL relies on an index-based approach, requiring knowledge of the peripheral instance index during both compilation and runtime, and this index might not align with the devicetree instance index.
As a prerequisite to refactor all those shim drivers to use the instance-based DT macros and to obtain the peripheral instance index at compile time as done in [f809614136](https://github.com/zephyrproject-rtos/zephyr/commit/f809614136c748707d365a1342128e0158145d55#diff-4bca4b738d2c995bd5b9a6e9bdf970d6c43fdfb33f2955e3093ac971228fec3aR404), remove the `u` prefix from the HAL instance count macros so that they can be used with `LISTIFY`.
> [!NOTE]
> There will be a separate PR in …
=> s32ze: remove `u` prefix from instance count macro

mcux/mcux-sdk/devices/MIMX9352/drivers/fsl_clock.c
clock source frequencies need to be initialized in mcux driver. we already have such fix, so port it here.
this is required by pr: https://github.com/zephyrproject-rtos/zephyr/pull/62755
=> imx93: port clock frequency initialization code

s32/CMakeLists.txt
Switch to use `CONFIG_SOC` to define the device name and CPU name needed to build MCUX drivers and device sources.
The SoC part number for S32 now makes reference to the actual part number of device as defined in datasheets and should't be used to define the CPU name.
=> s32: mcux: use the SoC name to set the device name

mcux/CMakeLists.txt, mcux/hal_nxp.cmake
In mcux-sdk, MCUX_DEVICE is defined with following CPU Core, so let's unify the macro definition with mcux-sdk, and use a new macro MCUX_DEVICE_PATH to define device PATH name.
=> cmake: unify MCUX_DEVICE with mcux_sdk

mcux/README, mcux/mcux-sdk/drivers/i3c/fsl_i3c.c, s32/mcux/devices/S32Z27/S32Z27_features.h, s32/mcux/devices/S32Z27/S32Z27_glue_mcux.h
This adds glue code to reuse i3c mcux sdk for s32z27. Alsoa dd patch on the mcux driver for fixing compiler warnings
=> Support I3C for S32Z27

s32/drivers/s32k3/BaseNXP/header/S32K344_LCU.h, s32/drivers/s32k3/BaseNXP/header/S32K344_TRGMUX.h
Make LCU_INSTANCE_COUNT and TRGMUX_INSTANCE_COUNT usable by Zephyr
=> Remove 'u' from Lcu and Trgmux instance count

s32/soc/s32z27/include/Netc_Eth_Ip_Features.h
Netc shim driver uses the macro FEATURE_NETC_ETH_NUMBER_OF_CTRLS with LISTIFY.
Remove 'u' suffix from macro so that it can be used with LISTIFY.
=> s32: soc: s32z27: netc: remove 'u' suffix from macro

s32/mcux/devices/S32K146/S32K146_device.h, s32/mcux/devices/S32K146/S32K146_features.h
Add definitions for LPI2C and LPSPI of S32K146 devices.
=> s32: mcux: s32k146: add LPI2C and LPSPI support

s32/mcux/devices/S32K344/S32K344_features.h
Removes the S32K3X4-0P55A-1P55A-ERRATA by disabling FSL_FEATURE_LPSPI_HAS_ERRATA_050456. This allows for lpspi to work correctly on mr_canhubk3.
=> s32k344: devices: Fix lpspi by removing errata.

s32/README, s32/drivers/s32k1/BaseNXP/header/S32K116_FLEXCAN.h, s32/drivers/s32k1/BaseNXP/header/S32K118_FLEXCAN.h, s32/drivers/s32k1/BaseNXP/header/S32K142W_FLEXCAN.h, s32/drivers/s32k1/BaseNXP/header/S32K142_FLEXCAN.h, s32/drivers/s32k1/BaseNXP/header/S32K144W_FLEXCAN.h, s32/drivers/s32k1/BaseNXP/header/S32K144_FLEXCAN.h, s32/drivers/s32k1/BaseNXP/header/S32K146_FLEXCAN.h, s32/drivers/s32k1/BaseNXP/header/S32K148_FLEXCAN.h, s32/mcux/devices/S32K146/S32K146_device.h, s32/mcux/devices/S32K146/S32K146_features.h
Support FlexCAN on S32K1xx devices:
- [patch] Rename fields and macros of FlexCAN device headers to allow compatibility with MCUX FlexCAN driver (see commit for details)
- Add definitions for MCUX FlexCAN driver for S32K146
=> Support FlexCAN on S32K1xx

mcux/README, mcux/middleware/mcux-sdk-middleware-usb/device/usb_device_lpcip3511.c
without this kStatus_USB_Error was always returned for kUSB_DeviceControlRun and kUSB_DeviceControlStop control types. let's do it as for ehci/khci.
this change fixes the tests/subsys/usb/device/usb.device test for lpcxpresso55s69_cpu0.
this is from https://github.com/nxp-mcuxpresso/mcux-sdk-middleware-usb/pull/6
=> mcux-sdk-middleware-usb: fix ip control return value for ip3511

mcux/README, mcux/hal_nxp.cmake, mcux/mcux-sdk/devices/MIMX9352/drivers/fsl_edma_soc_rev2.h, mcux/mcux-sdk/drivers/edma_rev2/driver_edma_rev2.cmake, mcux/mcux-sdk/drivers/edma_rev2/fsl_edma_rev2.c, mcux/mcux-sdk/drivers/edma_rev2/fsl_edma_rev2.h
This is needed because currently there's no EDMA API that can be used for all eDMA IPs found
on i.MX93, i.MX8QM, and i.MX8QXP.
This API also allows working with different eDMA variants
found on the same SoC (i.MX93 with eDMA3 and eDMA4 which are different)
Depends on: https://github.com/nxp-mcuxpresso/mcux-sdk/pull/152
=> drivers: Introduce revision 2 of the edma driver

s32/mcux/devices/S32K146/S32K146_device.h, s32/mcux/devices/S32K146/S32K146_features.h, s32/soc/s32k146/src/Clock_Ip_Cfg.c
Enable fsl_rtc.c driver on S32K146 devices.
=> s32: mcux: s32k146: enable RTC driver

mcux/hal_nxp.cmake
When using the new Zephyr EDMA driver, Zepyhr tries to include the old "edma" directory, which results in a build error since "driver_edma_rev2.cmake" is not placed inside that directory. To fix this, change the included directory's name to edma_rev2, which is the directory that contains the files associated with EDMA rev2 driver from NXP HAL.
=> hal_nxp.cmake: fix bad edma directory naming

mcux/README, mcux/mcux-sdk/components/css_pkc/src/comps/mcuxCsslMemory/inc/impl/mcuxCsslMemory_Compare_asm.h, mcux/mcux-sdk/drivers/common/fsl_common_arm.c
This commit fixes labels in inline assembly to use unique identifiers for internal labels.
This fix is required to be able to use LTO.
=> mcux: mcux-sdk: Fix labels in inline assembly

scr-hal.txt
The software content register file (scr-hal.txt) provides information about the NXP HAL. e.g. origin, license, location.
It is added for clarity.
=> License: summary of contents

mcux/hal_nxp.cmake
CONFIG_SOC_MIMX8QM_ADSP and CONFIG_SOC_MIMX8QXP_ADSP were renamed to match the soc name, so update here also.
While here, remove CONFIG_SOC_MIMX8QM_A53 since is not defined and used anywhere.
=> mcux: hal_nxp: update configs for ADSP

mcux/README, mcux/mcux-sdk/drivers/lpflexcomm/lpi2c/fsl_lpi2c.c
There was an error in the init and deinit functions where the LPFlexcomm registers was getting modified even if the flag LPFLEXCOMM_INIT_NOT_USED_IN_DRIVER was set.
PR submitted to internal mcux-sdk-github repo as well
=> drivers: lpi2c: Fix the interaction with LPFlexcomm driver

mcux/hal_nxp.cmake
If the Zephyr ESAI driver is enabled this also means we should include the HAL ESAI driver since the former depends on the latter.
=> mcux: hal_nxp: include HAL ESAI driver if Zephyr ESAI driver is enabled

mcux/README, mcux/mcux-sdk/devices/LPC5534/LPC5534_features.h, mcux/mcux-sdk/devices/LPC5536/LPC5536_features.h, mcux/mcux-sdk/devices/LPC55S36/LPC55S36_features.h
Three LPC devices were using the HAS_NO_WAITEN
macro definition when the devices had the WAIT
ENABLE BIT for PWM on their individual device
header file.
PR submitted to internal mcux-sdk-github repo as well.
=> devices: LPC55XXX: Removed incorrect pwm defs

mcux/README
Patch has already been merged to MCUX-SDK via https://github.com/nxp-mcuxpresso/mcux-sdk/pull/182.
=> devices: MIMX8UD7: add definition for LPUART_RX_TX_IRQS

mcux/README, mcux/mcux-sdk/devices/MIMX8UD7/drivers/fsl_edma_soc_rev2.h
Patch has already been merged to MCUX-SDK via https://github.com/nxp-mcuxpresso/mcux-sdk/pull/181.
=> devices: MIMX8UD7: add EDMA rev2 support

s32/soc/s32k146/src/Clock_Ip_Cfg.c
Set the RTC clock source to the 32KHz internal oscillator.
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/71289
=> s32: s32k146: set RTC clock source to internal oscillator

mcux/hal_nxp.cmake
Add build support for LPCMP driver
=> mcux: hal_nxp.cmake: Add build support for LPCMP driver

mcux/README, mcux/hal_nxp.cmake, mcux/middleware/mcux-sdk-middleware-usb/device/usb_device_ehci.c, mcux/middleware/mcux-sdk-middleware-usb/device/usb_device_lpcip3511.c, mcux/middleware/mcux-sdk-middleware-usb/device/usb_device_mcux_drv_port.h
Add the NXP USB Device controllers support in Zephyr.
Support EHCI and IP3511, verified on RT1060, LPC55S69 and RT685.
=> Enable NXP USB Device controllers (udc_mcux) in Zephyr

mcux/README, mcux/mcux-sdk/drivers/csi/fsl_csi.c, mcux/mcux-sdk/drivers/csi/fsl_csi.h
Currently, the camera framerate is divided by two. This is because the driver only puts the full buffer to the queue and calls the callback at half of the interrupt rate (when there are at least 2 active framebuffers).
This issue is not really visible when using more than two buffers and the application does not hold the full buffer for too long before submitting it again to the empty buffers queue. But if we use only two buffers, the framerate is clearly reduced (by a factor of two).
Especially, when CSI_TransferGetFullBuffer() get called inside the callback function (as in Zephyr RTOS), framerate is always reduced by a factor of two despite of the number of buffers used.
Rework the driver to fix these issues as well as to clean up the logics.
The corresponding SDK PR is here …
=> drivers: csi: Rework to fix the low framerate issue

mcux/README, mcux/mcux-sdk/drivers/flexio/fsl_flexio.c, mcux/mcux-sdk/drivers/flexio/fsl_flexio.h, s32/mcux/devices/S32K344/S32K344_features.h, s32/mcux/devices/S32K344/S32K344_glue_mcux.h
This commit enables the existing mcux flexio driver to support Flexio IP on S32 SoCs as well.
=> mcux: Enable flexio hal driver to support flexio IP on S32 SoCs

mcux/README, mcux/mcux-sdk/drivers/elcdif/fsl_elcdif.c
Currently, when setting pixel format, all the previous values of the CTRL1 register, even not related to pixel format, are unwantedly cleared. This leads to some erroneous behaviors, for example, the interrupts will be disabled.
Fix it by modifying only the related bits of the CTRL1 register.
This was also merged to github mcux-sdk: https://github.com/nxp-mcuxpresso/mcux-sdk/commit/84cd68607886ca810c239e7b95b8b7d497096c9b
=> drivers: elcdif: Fix register writting issue in SetPixelFormat

CMakeLists.txt, mcux/middleware/mcux-sdk-middleware-connectivity-framework/connectivity_framework.cmake, zephyr/src/CMakeLists.txt, zephyr/src/rw61x/CMakeLists.txt, zephyr/src/rw61x/rw61x_cpu1.c, zephyr/src/rw61x/rw61x_cpu2.c
Make use of generate_inc_file_for_target() to convert the firmware binaries into C arrays which will be linked by the application and sourced when loading the CPU1 and CPU2 firmwares.
Put the firmwares into sections to allow for more control on placement.
=> Support monolithic app

mcux/hal_nxp.cmake, mcux/middleware/mcux-sdk-middleware-usb/device/usb_device_ehci.c, mcux/middleware/mcux-sdk-middleware-usb/device/usb_device_lpcip3511.c, mcux/middleware/mcux-sdk-middleware-usb/device/usb_device_mcux_drv_port.h
Remove the 'USB' prefix in the Kconfig macro.
Update controller drivers to still include some head files that can be controlled by MCUX USB stack macro.
Replace Zephyr Kconfig marco with MCUX USB macro in usb_device_mcux_drv_port.h
=> middleware: usb: the MCUX udc Kconfig macro is changed.

mcux/hal_nxp.cmake
Include cache driver in case of CONFIG_HAS_MCUX_CACHE is enabled.
=> build: hal_nxp: add cache driver for Cortex-A Core

s32/mcux/devices/S32Z270/S32Z270_features.h
According to S32Z2 RM, RTU.PIT has 6 channels.
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/74360
=> s32: mcux: s32z270: fix RTU.PIT number of channels

s32/mcux/devices/S32K344/S32K344_features.h
Add missing define to be able to build Zephyr EDMAv3 driver.
=> s32: s32k344: add missing DMAMUX count define

mcux/README, mcux/mcux-sdk/drivers/adc12/fsl_adc12.c, s32/drivers/s32k1/BaseNXP/header/S32K146_ADC.h, s32/mcux/devices/S32K146/S32K146_device.h, s32/mcux/devices/S32K146/S32K146_features.h
Enable fsl_adc12 driver on S32K146 devices.
We are getting everything ready to support ADC on the S32K146/8.
Adaption in the register header file is there to make it compatible with the existing ADC driver (kinetis-adc12).
The Zephyr PR is: https://github.com/zephyrproject-rtos/zephyr/pull/75723
=> s32: mcux: s32k146: enable ADC driver

s32/mcux/devices/S32Z270/S32Z270_features.h, s32/mcux/devices/S32Z270/S32Z270_glue_mcux.h
Add LPI2C instance base addresses and module features to support using LPI2C MCUX driver.
=> Add support for LPI2C on S32Z27x

s32/README, s32/drivers/s32ze/BaseNXP/header/S32Z2_DMAMUX.h, s32/mcux/devices/S32Z270/S32Z270_device.h, s32/mcux/devices/S32Z270/S32Z270_features.h, s32/mcux/devices/S32Z270/S32Z270_glue_mcux.h, s32/mcux/devices/S32Z270/drivers/driver_memory.cmake
Add EDMAv3 instances base addresses and module features to support using the EDMA MCUX driver.
=> Support edma3 for s32z270dc2

dts/nxp/s32/S32Z27-BGA400-pinctrl.h, dts/nxp/s32/S32Z27-BGA594-pinctrl.h, mcux/README, mcux/mcux-sdk/drivers/dspi/fsl_dspi.c, mcux/mcux-sdk/drivers/dspi/fsl_dspi.h, mcux/mcux-sdk/drivers/dspi/fsl_dspi_edma.c, mcux/mcux-sdk/drivers/dspi/fsl_dspi_edma.h, s32/README, s32/drivers/s32ze/BaseNXP/header/S32Z2.h, s32/mcux/devices/S32Z270/S32Z270_device.h, s32/mcux/devices/S32Z270/S32Z270_features.h, s32/mcux/devices/S32Z270/S32Z270_glue_mcux.h
This PR to add support dspi for s32z27x devices
Tested on tests\drivers\spi\spi_loopback\drivers.spi.s32z_dspi.loopback
------ TESTSUITE SUMMARY START ------
SUITE PASS - 100.00% [spi_loopback]: pass = 1, fail = 0, skip = 0, total = 1 duration = 0.366 seconds
PASS - [spi_loopback.test_spi_loopback] duration = 0.366 seconds
------ TESTSUITE SUMMARY END ------
=> Add support dspi for s32z270dc2

mcux/hal_nxp.cmake
- Added includes of OSA when used with USB MW
- Added include path on global level to avoid undefined #include <fsl_os_abstraction.h> and other headers
=> mcux: middleware: usb: fix USB MW to use new OSA

mcux/README, mcux/mcux-sdk/drivers/irqsteer/fsl_irqsteer.c
For IRQ_STEER, lower CHn_MASK register indexes are used to mask higher interrupt IDs. For instance, in the case of i.MX8MP, the mapping is as follows:
CHn_MASK4 => masks interrupts [31:0]
CHn_MASK3 => masks interrupts [63:32]
CHn_MASK2 => masks interrupts [95:64]
CHn_MASK1 => masks interrupts [127:96]
CHn_MASK0 => masks interrupts [159:128]
The `IRQSTEER_GetRegIndex()` function is used to fetch the CHn_MASK register index based on a given slice. The term "slice" is used to refer to an index of a CHn_MASK register in the set of CHn_MASK registers assigned to a certain master. Assuming the following partition scheme (i.MX8MP):
{ CHn_MASK4 } is assigned to MASTER0
{ CHn_MASK3, CHn_MASK2 } is assigned to MASTER1
{ CHn_MASK1, CHn_MASK0 } is assiged to MASTER2
CHn_MASK3 would be at slice …
=> drivers: irqsteer: adjust CHn_MASK index computation

mcux/mcux-sdk/components/rpmsg/fsl_adapter_rfimu.c
Destroy cpu1 and cpu3 imu task but not set flag when cpu3 reset.
because flag is not set, so zephyr task list is loop when create
cpu1 and cpu3 task again, and will hang when pick next task
Don't reset imu_task_flag when destroying imu task when deinit imu
=> mcux: fix hang when cpu3 reset

mcux/README, mcux/mcux-sdk/drivers/cache/cache64/fsl_cache.c
CACHE64_GetInstanceByAddr() asserts when an address is passed in that is not managed by the CACHE64 controller. This is incorrect behavior, as the CACHE64 driver checks to see if the returned instance number is out of range when using this function, so we should not assert here.
Remove the assert so that cache invalidation functions can be used with addresses not the CACHE64 controller's range.
=> mcux: mcux-sdk: drivers: cache64: remove invalid assert in GetInstance

mcux/middleware/CMakeLists.txt
Enable connectivity_framework to be used by Openthread RCP
=> mcux: middleware: enable FWK for Openthread

mcux/middleware/wifi_nxp/wifidriver/wpa_supp_if/rtos_wpa_supp_if.c
After hostap upmerge the signal data structure is moved.
=> middleware: wifi_nxp: Fix build errors with latest hostapd

mcux/scripts/pinctrl/README.md
Fix a broken link to the MCUX SDK builder within the pin control scripts readme section
=> mcux: scripts: pinctrl: fix broken link to MCUX SDK builder

mcux/middleware/mcux-sdk-middleware-connectivity-framework/connectivity_framework.cmake, zephyr/src/rw61x/CMakeLists.txt, zephyr/src/rw61x/rw61x_cpu2.c
To simplify how coexistence between BLE and 15.4 works, we decided to choose the cpu2 firmware based on which SoC is used. If RW612 is used, then we use the combo firmware.
If RW610 is used, then we use the ble only firmware.
MONOLITHIC_BT and MONOLITHIC_IEEE802154 configs have been combined into a single one: MONOLITHIC_NBR.
We also unify the fw array symbol to `fw_cpu2` and make it transparent to the connectivity_framework by using the preprocessor.
=> zephyr: rw61x: rework cpu2 monolithic handling

mcux/hal_nxp.cmake
Enable mu1 for i.MX8ULP, that is MIMX8UD7.
=> mcux: hal_nxp: Enable MU1 driver for 8ULP

mcux/mcux-sdk/drivers/ccm32k/driver_ccm32k.cmake
Fix message should say ccm32k not gpio
there is no zephyr side PR because this is extremely trivial, it can get pulled in by any other manifest change
=> mcux-sdk: Fix message for ccm32k

zephyr/module.yml
Support fetch wifi/bt/combo fw with p24 version.
=> zephyr: support fetch wifi/bt/combo fw with p24 version

mcux/mcux-sdk/drivers/sai/fsl_sai.c
According the RM document, RT1170 58.3.3 (should be same for other MCU which has a similiar SAI IP):
"A valid frame sync is also ignored (slave mode) or not generated (master mode) for the first four bit clock cycles after enabling the transmitter or receiver."
but in fact, we found master side send out a valid frame sync at the 3rd bit clock cycles which cause this frame sync is ignored by the slave side and frame data lost.
To workaround this issue, bit clock is enabled before TE/RE.
=> drivers: sai: the 1st frame synchronization signal lost in slave side

mcux/middleware/CMakeLists.txt
Include mcux-secure-subsystem files only if zephyr entropy macro `CONFIG_ENTROPY_HAS_DRIVER` is enabled.
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/85815
=> mcux: put mcux-secure-subsystem files under zephyr entropy

mcux/README, mcux/middleware/mcux-sdk-middleware-usb/device/usb_device_ehci.c, mcux/middleware/mcux-sdk-middleware-usb/device/usb_device_lpcip3511.c
Zephyr USB device stack handles the zlt and the NXP usb controller drivers process the control endpoint zlt defaultly, disable it in controller driver if in Zephyr environment. The original NXP usb controller drivers disabled it, but the change is overwritten by mistake by 6d708041ce32d3a48622e9344663b677558fff4d commit.
=> mcux: mcux-sdk-middleware-usb: disable usb controller zlt

zephyr/module.yml
This new version of the BLE controller is aligned with the one for MCXW72. It contains a fix which consists of returning an HCI command complete event when setting the BD address.
We need both platforms to be aligned on this behavior to correctly implement our zephyr hci_nxp driver.
=> zephyr: blobs: update MCXW71 BLE controller to MCUXSDK 24.12.00 release

mcux/hal_nxp.cmake, mcux/mcux-sdk/drivers/netc/driver_netc.cmake
=> NETC driver cmake fix up

s32/soc/s32z270/src/Clock_Ip_Cfg.c
Configure the divider for ETH 1 RX to achive 125Mhz for Rx RGMII
=> s32ds: s32z upstream: correct clock configuration for ETH1 RX

mcux/middleware/wifi_nxp/wifidriver/wpa_supp_if/rtos_wpa_supp_if.c, mcux/middleware/wifi_nxp/wlcmgr/wlan.c
Include new header file to support hostapd source code split in glue layer.
=> middleware: wifi_nxp: Include new hostap glue layer header file

mcux/middleware/mcux-sdk-middleware-connectivity-framework/platform/rw61x/fwk_platform_ble.c, mcux/middleware/mcux-sdk-middleware-connectivity-framework/platform/rw61x/fwk_platform_hdlc.c, mcux/middleware/wifi_nxp/CMakeLists.txt, mcux/middleware/wifi_nxp/wifidriver/wifi-imu.c, mcux/middleware/wifi_nxp/wifidriver/wifi.c
Update imu adapter to latest and
use cmake in imu_adapter folder instead of rpmsg.
=> middleware: wifi_nxp: align imu adapter with SDK Next Generation

mcux/mcux-sdk/devices/MIMX9352/drivers/fsl_clock.h, mcux/mcux-sdk/drivers/usdhc/fsl_usdhc.c, mcux/mcux-sdk/drivers/usdhc/fsl_usdhc.h
1.  drivers: usdhc: change the driver to be aarch64 compatible
2.  devices: MIMX9352: fsl_clock: Add missing definitions for USDHC
=> add SDHC support on imx93

mcux/middleware/wifi_nxp/wlcmgr/wlan_enhanced_tests.c, mcux/middleware/wifi_nxp/wlcmgr/wlan_txpwrlimit_cfg.c
Support setting TX power limit file to override the default one for customer's board.
=> mcux: wifi: nxp: support override TX power limit file

mcux/middleware/CMakeLists.txt
Switching on IEEE 802.15.4 dependencies at any mode instead of only when using openthread or NET_L2.
=> mcux: ieee802154: enabled any mode to mcxw ieee802154 driver

mcux/mcux-sdk-ng/drivers/netc/fsl_netc_timer.c, mcux/mcux-sdk-ng/drivers/netc/fsl_netc_timer.h
The TMR_CTRL[period] is integral period of the timer clock in ns, while TMR_ADD represents the fractional clock period. So TMR_CTRL[period] should be updated too.
=> mcux: netc: ptp_clock: Correct function NETC_TimerAdjustFreq

mcux/mcux-sdk-ng/devices/i.MX/i.MX95/MIMX9596/drivers/fsl_memory.h
find in support edma test case, the start address is not right.
=> devices: MIMX9596: fsl_memory: corrected the starting value of M7 memory offset

mcux/middleware/wifi_nxp/port/net/zephyr/net.c
The network management event type is changed from uint32_t to uint64_t so update the code to prevent compilation issues.
=> mcux: wifi_nxp: Update the net_mgmt event type to uint64_t

zephyr/module.yml
upgrade RW612 FW to version 6.p41,
upgrade IW610 FW to version 5.p67.
=> zephyr: upgrade RW612 p41 FW and IW610 p67 FW

mcux/middleware/wifi_nxp/CMakeLists.txt, mcux/middleware/wifi_nxp/wifidriver/wifi.c
- When using code relocation, add the NOKEEP flag to discard unused code to reduce ITCM memory usage.
- move wifidriver/sdio.c and /subsys/sd/sdio.c into ITCM.
move nxp_wifi_send() and nxp_wifi_recv() into ITCM.
Use DTCM_TEXT instead of DTCM, then only text code will be relocated into DTCM.
- remove unused code in wifi_core_task for RW610.
=> mcux: upgrade wifi_nxp

mcux/mcux-sdk-ng/drivers/irqsteer_1/CMakeLists.txt, mcux/mcux-sdk-ng/drivers/irqsteer_1/fsl_irqsteer.c, mcux/mcux-sdk-ng/drivers/irqsteer_1/fsl_irqsteer.h
Fix build errors,
- drivers/irqsteer_1/fsl_irqsteer.h:187:56: error: pointer of type void * used in arithmetic [-Werror=pointer-arith]
=> mcux-sdk-ng: drivers: irqsteer_1: fix build errors

mcux/README, mcux/mcux-sdk/devices/MKV56F24/MKV56F24.h
The MKV56F24 device doesn't contain CAN2 peripheral. Remove it from the device header.
=> mcux: mcux-sdk: devices: fix MKV56F24.h wrong macro

mcux/mcux-sdk-ng/drivers/common/fsl_common_arm.h, mcux/mcux-sdk-ng/drivers/netc/netc_hw/fsl_netc_hw.c, mcux/mcux-sdk/devices/MIMX9596/MIMX9596_ca55_features.h
1. drivers: netc: make the driver to be aarch64 compatible
2. mcux-sdk: MIMX9596_ca55: disable FSL_FEATURE_NETC_HAS_ERRATA_051711
3. mcux-sdk: MIMX9596_ca55: fix A-Core header file regard of netc struct definition
4. fsl_common_arm: Fix comment sign issue on different architectures
=> enable NETC on imx95 Cortex-A55

mcux/middleware/wifi_nxp/incl/port/mbedtls/wpa_supp_dcp_mbedtls_config.h, mcux/middleware/wifi_nxp/incl/port/mbedtls/wpa_supp_els_pkc_mbedtls_config.h
Added and enable below flags in mbedtls config files: PSA_WANT_ALG_HKDF_EXTRACT
PSA_WANT_ALG_HKDF_EXPAND
MBEDTLS_PSA_BUILTIN_ALG_HKDF_EXTRACT
MBEDTLS_PSA_BUILTIN_ALG_HKDF_EXPAND
=> mcux: wifi_nxp: Add TLSv1.3 prerequisites in mbedtls config files

mcux/mcux-sdk-ng/drivers/enet/fsl_enet.h
ENET provides 1588_EVENT_IN signals to latch the current timer value in TCCRn when a rising edge is detected. This pull request exposes the latched timer value via ENET_Ptp1588GetCapture.
=> Expose Timestamp of 1588_EVENT_IN

mcux/middleware/wifi_nxp/wifidriver/wifi-imu.c
After running 'kernel reboot' cmd on coex application, zephyr os clean bss section, IMU13 IRQ event data set as 0, then CPU3 receive IMU13 IRQ from CPU1, need access IMU13 IRQ event, cause hang.
Put enable IMU13 IRQ operation after related task and event created to fix this issue.
=> mcux: wifi_nxp: Enable IMU IRQ after event initialized
